package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import baseDatos.bdSegura;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    \n");
      out.write("    <script src=\"encriptar/md5.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script  type=\"text/javascript\"> \n");
      out.write("            function modificarClave(texto){\n");
      out.write("                var claveCifrada = hex_md5(texto);\n");
      out.write("                document.getElementById(\"idclave\").value = claveCifrada;\n");
      out.write("            }\n");
      out.write("               </script> \n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0\">\n");
      out.write("    <title>Hotel</title>\n");
      out.write("    <meta name=\"keywords\" content=\"\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <link rel=\"shortcut icon\" href=\"recursos/images/favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"recursos/images/apple-touch-icon.png\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"recursos/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"recursos/css/style.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"recursos/css/responsive.css\">\n");
      out.write("    <link id=\"\" rel=\"stylesheet\" href=\"recursos/css/colors/orange.css\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("    <script src=\"recursos/js/modernizer.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("                        \n");
      out.write("<body>\n");
      out.write("    \n");
      out.write("    <div id=\"loader\">\n");
      out.write("        <div id=\"status\"></div>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"site-header\">\n");
      out.write("        <header id=\"header\" class=\"header-block-top\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"main-menu\">\n");
      out.write("                      \n");
      out.write("                        <nav class=\"navbar navbar-default\" id=\"mainNav\">\n");
      out.write("                            <div class=\"navbar-header\">\n");
      out.write("                                <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\n");
      out.write("                                    <span class=\"sr-only\">navigation</span>\n");
      out.write("                                    <span class=\"icon-bar\"></span>\n");
      out.write("                                    <span class=\"icon-bar\"></span>\n");
      out.write("                                    <span class=\"icon-bar\"></span>\n");
      out.write("                                </button>\n");
      out.write("                                <div class=\"logo\">\n");
      out.write("                                    <a class=\"navbar-brand js-scroll-trigger logo-header\" href=\"#\">\n");
      out.write("                                        </a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div id=\"navbar\" class=\"navbar-collapse collapse\">\n");
      out.write("                                <center><ul class=\"nav navbar-nav navbar-center\">\n");
      out.write("                                    \n");
      out.write("                                    <li class=\"active\"><a href=\"#footer\">Inicio</a></li>\n");
      out.write("                                    <li><a href=\"#about\">Ingresar </a></li>\n");
      out.write("                                    <li><a href=\"#gallery\">Habitaciones</a></li>\n");
      out.write("                                    <li><a href=\"#menu\">Localidades</a></li>\n");
      out.write("                                    <li><a href=\"#banner\">registrarme</a></li>\n");
      out.write("                                    <li><a href=\"#\">Quienes Somos</a></li>\n");
      out.write("                                </ul></center>\n");
      out.write("                            </div>\n");
      out.write("                        </nav>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("   \n");
      out.write("     <div id=\"footer\" class=\"footer-box pad-top-70\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"footer-in-main\">\n");
      out.write("                        <div class=\"footer-logo\">\n");
      out.write("                            <div class=\"text-center\">\n");
      out.write("                                <img src=\"recursos/images/CasaMar.png\"  width=\"550\" height=\"400\" alt=\"\" >\n");
      out.write("                                <div class=\"banner-text\">\n");
      out.write("                                 <h2>Las Mejores Vacaciones de tu vida</h2>\n");
      out.write("                                </div>\n");
      out.write("                                <h2><span class=\"typer\" id=\"some-id\" data-delay=\"100\" data-delim=\":\" data-words=\"Vive:disfruta: y celebra...\" data-colors=\"red\"></span><span class=\"cursor\" data-cursorDisplay=\"_\" data-owner=\"some-id\"></span></h2>\n");
      out.write("                            <p>HOTEL CASA MAR RESORT</p>\n");
      out.write("                            <div class=\"book-btn\">\n");
      out.write("                            </div>\n");
      out.write("                            <a href=\"#about\"></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("   \n");
      out.write("\n");
      out.write("    <div id=\"about\" class=\"about-main pad-top-100 pad-bottom-100\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-6 col-md-6 col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"wow fadeIn\" data-wow-duration=\"1s\" data-wow-delay=\"0.1s\"><br>\n");
      out.write("                       <br> <center>   <h2 class=\"block-title\"> Bienvenido </h2>\n");
      out.write("                            <h2 class=\"block-title\"> Ingrese sus datos  </h2></center>\n");
      out.write("                    \n");
      out.write("    \n");
      out.write("            <form action=\"#!\">\n");
      out.write("               <div class=\"mb-3\">\n");
      out.write("    <label  class=\"form-label\">Id Usuario</label>\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"idusuario\" name=\"txtusuario\">\n");
      out.write("              </div> \n");
      out.write("              <div class=\"mb-3\">\n");
      out.write("    <label  class=\"form-label\">Contraseña</label>\n");
      out.write("                <input type=\"password\" class=\"form-control\" id=\"idclave\" name=\"txtclave\">\n");
      out.write("              </div>\n");
      out.write("                <br>\n");
      out.write("           <center> \n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\" name=\"ingresar\"  value=\"ingresar\" onclick=\"modificarClave(document.getElementById('idclave').value)\">Ingresar</button>\n");
      out.write("         </center>\n");
      out.write("        </form> \n");
      out.write("                       \n");
      out.write("      \n");
      out.write("  \n");
      out.write("  </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- end col -->\n");
      out.write("                <div class=\"col-lg-6 col-md-6 col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"wow fadeIn\" data-wow-duration=\"1s\" data-wow-delay=\"0.1s\">\n");
      out.write("                        <div class=\"about-images\">\n");
      out.write("                            <img class=\"about-inset\" src=\"recursos/images/logo14.png\" alt=\"About Inset Image\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("         \n");
      out.write("            </div>\n");
      out.write("      \n");
      out.write("        </div>\n");
      out.write(" \n");
      out.write("    </div>\n");
      out.write("     ");

            if(request.getParameter("ingresar")!=null)
            {
            String user=request.getParameter("txtusuario");
            String pass=request.getParameter("txtclave");
            String rol="";
            try
            {
            bdSegura dbs= new bdSegura();
            Connection conex= dbs.conSeg();
            PreparedStatement psmt=null;
            
            String consulta="Select Usuario, Clave, TipoUsuario from usuarios where Usuario like ? and clave like ? ";
            psmt=conex.prepareStatement(consulta);
            psmt.setString(1,user);
             psmt.setString(2,pass);
            
            ResultSet rs=psmt.executeQuery();
            
            String centinela="n";
            
            while(rs.next())
            {
             centinela="s";
             rol=rs.getString(3);
                
            }
            if( centinela.equals("s"))
            {
            session.setAttribute("s_usuario",user);
            session.setAttribute("s_rol", rol);
            if(rol.equals("Admin")){
            request.getRequestDispatcher("usuarioAdmin.jsp").forward(request, response);
            }
            if(rol.equals("Cliente")){
            request.getRequestDispatcher("usuarioCliente.jsp").forward(request, response);
            }
            if(rol.equals("Vendedor")){
            request.getRequestDispatcher("usuarioVendedor.jsp").forward(request, response);
            }
            }else {
            
                
      out.write("\n");
      out.write("                <div class=\"alert alert-danger\" role=\"alert\" align=\"center\">Usuario o Clave, Incorrecta</div>\n");
      out.write("                \n");
      out.write("                ");

            
            }
                psmt.close();
                conex.close();

            } catch (Exception e)
               {
              e.printStackTrace();
               }
            
            
            }
          
      out.write("\n");
      out.write("          \n");
      out.write("          ");

            
            
        if(request.getParameter("registro")!=null)
        {
        request.getRequestDispatcher("registrarUsuario.jsp").forward(request, response);
        }
        
        
      out.write("   \n");
      out.write("        \n");
      out.write("                  \n");
      out.write("                <!-- end col -->\n");
      out.write("                <div class=\"col-lg-6 col-md-6 col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"wow fadeIn\" data-wow-duration=\"1s\" data-wow-delay=\"0.1s\">\n");
      out.write("                        <div class=\"about-images\">\n");
      out.write("                            <img class=\"about-inset\" src=\"recursos/images/logo14.png\" alt=\"About Inset Image\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("         \n");
      out.write("           \n");
      out.write("      \n");
      out.write("     \n");
      out.write(" \n");
      out.write("  \n");
      out.write("\n");
      out.write("    <div id=\"gallery\"  class=\" special-menu pad-top-100 parallax\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"wow fadeIn\" data-wow-duration=\"1s\" data-wow-delay=\"0.1s\"><BR><BR><BR><BR>\n");
      out.write("                        <h2 class=\"block-title color-white text-center\"> Nuestras Habitaciones </h2>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"special-box\">\n");
      out.write("                        <div id=\"owl-demo\">\n");
      out.write("                            <div class=\"item item-type-zoom\">\n");
      out.write("                                <a href=\"#\" class=\"item-hover\">\n");
      out.write("                                    <div class=\"item-info\">\n");
      out.write("                                        <div class=\"headline\">\n");
      out.write("                                            Habitacion eLEGANTE CON VISTA AL MAR\n");
      out.write("                                            <div class=\"line\"></div>\n");
      out.write("                                            <div class=\"dit-line\">XXXXXXX XXXXXXX</div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"item-img\">\n");
      out.write("                                    <img src=\"recursos/images/hotel1.jpg\" width=\"550\" height=\"400\" alt=\"sp-menu\">\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"item item-type-zoom\">\n");
      out.write("                                <a href=\"#\" class=\"item-hover\">\n");
      out.write("                                    <div class=\"item-info\">\n");
      out.write("                                        <div class=\"headline\">\n");
      out.write("                                            XXXXXX XXXXXX\n");
      out.write("                                            <div class=\"line\"></div>\n");
      out.write("                                            <div class=\"dit-line\"> XXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX.</div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"item-img\">\n");
      out.write("                                    <img src=\"recursos/images/hotel2.jpg\" width=\"440\" height=\"560\" alt=\"sp-menu\">\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"item item-type-zoom\">\n");
      out.write("                                <a href=\"#\" class=\"item-hover\">\n");
      out.write("                                    <div class=\"item-info\">\n");
      out.write("                                        \n");
      out.write("                                        <div class=\"headline\">\n");
      out.write("                                           XXXXXXXXXX\n");
      out.write("                                            <div class=\"line\"></div>\n");
      out.write("                                            <div class=\"dit-line\">XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX.</div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"item-img\">\n");
      out.write("                                    <img src=\"recursos/images/hotel3.jpg\" width=\"440\" height=\"560\" alt=\"sp-menu\">\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"item item-type-zoom\">\n");
      out.write("                                <a href=\"#\" class=\"item-hover\">\n");
      out.write("                                    <div class=\"item-info\">\n");
      out.write("                                        <div class=\"headline\">\n");
      out.write("                                            XXXXXXXX\n");
      out.write("                                            <div class=\"line\"></div>\n");
      out.write("                                            <div class=\"dit-line\">XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX</div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"item-img\">\n");
      out.write("                                    <img src=\"recursos/images/hotel4.jpg\" alt=\"sp-menu\">\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"item item-type-zoom\">\n");
      out.write("                                <a href=\"#\" class=\"item-hover\">\n");
      out.write("                                    <div class=\"item-info\">\n");
      out.write("                                        <div class=\"headline\">\n");
      out.write("                                           XXXXXXXX\n");
      out.write("                                            <div class=\"line\"></div>\n");
      out.write("                                            <div class=\"dit-line\">XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX.</div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"item-img\">\n");
      out.write("                                    <img src=\"recursos/images/hotel5.jpg\" alt=\"sp-menu\"><BR><BR>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                   \n");
      out.write("                </div>\n");
      out.write("               \n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("       \n");
      out.write("    </div>\n");
      out.write("   \n");
      out.write("\n");
      out.write("    <div id=\"menu\" class=\"gallery-main pad-top-100 pad-bottom-100\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"wow fadeIn\" data-wow-duration=\"1s\" data-wow-delay=\"0.1s\">\n");
      out.write("                        <h2 class=\"block-title text-center\">\n");
      out.write("\t\t\t\t\t\tLocalidades\t\n");
      out.write("\t\t\t\t\t</h2>\n");
      out.write("                        <p class=\"title-caption text-center\">La mejor felicidad se disfruta en familia </p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"gal-container clearfix\">\n");
      out.write("                        <div class=\"col-md-8 col-sm-12 co-xs-12 gal-item\">\n");
      out.write("                            <div class=\"box\">\n");
      out.write("                                <a href=\"#\" data-toggle=\"modal\" data-target=\"#1\">\n");
      out.write("                                    <img src=\"recursos/images/9.jpg\" alt=\"\" />\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"modal fade\" id=\"1\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("                                    <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                                        <div class=\"modal-content\">\n");
      out.write("                                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">×</span></button>\n");
      out.write("                                            <div class=\"modal-body\">\n");
      out.write("                                                <img src=\"recursos/images/9.jpg\" alt=\"\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-12 description\">\n");
      out.write("                                                <h4></h4>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4 col-sm-6 co-xs-12 gal-item\">\n");
      out.write("                            <div class=\"box\">\n");
      out.write("                                <a href=\"#\" data-toggle=\"modal\" data-target=\"#2\">\n");
      out.write("                                    <img src=\"recursos/images/2.jpg\" alt=\"\" />\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"modal fade\" id=\"2\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("                                    <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                                        <div class=\"modal-content\">\n");
      out.write("                                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">×</span></button>\n");
      out.write("                                            <div class=\"modal-body\">\n");
      out.write("                                                <img src=\"recursos/images/2.jpg\" alt=\"\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-12 description\">\n");
      out.write("                                                <h4></h4>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4 col-sm-6 co-xs-12 gal-item\">\n");
      out.write("                            <div class=\"box\">\n");
      out.write("                                <a href=\"#\" data-toggle=\"modal\" data-target=\"#3\">\n");
      out.write("                                    <img src=\"recursos/images/3.jpg\" alt=\"\" />\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"modal fade\" id=\"3\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("                                    <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                                        <div class=\"modal-content\">\n");
      out.write("                                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">×</span></button>\n");
      out.write("                                            <div class=\"modal-body\">\n");
      out.write("                                                <img src=\"recursos/images/3.jpg\" alt=\"\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-12 description\">\n");
      out.write("                                                <h4></h4>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4 col-sm-6 co-xs-12 gal-item\">\n");
      out.write("                            <div class=\"box\">\n");
      out.write("                                <a href=\"#\" data-toggle=\"modal\" data-target=\"#4\">\n");
      out.write("                                    <img src=\"recursos/images/4.jpg\" alt=\"\" />\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"modal fade\" id=\"4\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("                                    <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                                        <div class=\"modal-content\">\n");
      out.write("                                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">×</span></button>\n");
      out.write("                                            <div class=\"modal-body\">\n");
      out.write("                                                <img src=\"recursos/images/4.jpg\" alt=\"\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-12 description\">\n");
      out.write("                                                <h4></h4>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4 col-sm-6 co-xs-12 gal-item\">\n");
      out.write("                            <div class=\"box\">\n");
      out.write("                                <a href=\"#\" data-toggle=\"modal\" data-target=\"#5\">\n");
      out.write("                                    <img src=\"recursos/images/5.jpg\" alt=\"\" />\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"modal fade\" id=\"5\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("                                    <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                                        <div class=\"modal-content\">\n");
      out.write("                                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">×</span></button>\n");
      out.write("                                            <div class=\"modal-body\">\n");
      out.write("                                                <img src=\"recursos/images/5.jpg\" alt=\"\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-12 description\">\n");
      out.write("                                                <h4></h4>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4 col-sm-6 co-xs-12 gal-item\">\n");
      out.write("                            <div class=\"box\">\n");
      out.write("                                <a href=\"#\" data-toggle=\"modal\" data-target=\"#9\">\n");
      out.write("                                    <img src=\"recursos/images/6.jpg\" alt=\"\" />\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"modal fade\" id=\"9\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("                                    <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                                        <div class=\"modal-content\">\n");
      out.write("                                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">×</span></button>\n");
      out.write("                                            <div class=\"modal-body\">\n");
      out.write("                                                <img src=\"recursos/images/6.jpg\" alt=\"\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-12 description\">\n");
      out.write("                                                <h4></h4>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-8 col-sm-12 co-xs-12 gal-item\">\n");
      out.write("                            <div class=\"box\">\n");
      out.write("                                <a href=\"#\" data-toggle=\"modal\" data-target=\"#10\">\n");
      out.write("                                    <img src=\"recursos/images/7.jpg\" alt=\"\" />\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"modal fade\" id=\"10\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("                                    <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                                        <div class=\"modal-content\">\n");
      out.write("                                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">×</span></button>\n");
      out.write("                                            <div class=\"modal-body\">\n");
      out.write("                                                <img src=\"recursos/images/7.jpg\" alt=\"\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-12 description\">\n");
      out.write("                                                <h4></h4>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4 col-sm-6 co-xs-12 gal-item\">\n");
      out.write("                            <div class=\"box\">\n");
      out.write("                                <a href=\"#\" data-toggle=\"modal\" data-target=\"#11\">\n");
      out.write("                                    <img src=\"recursos/images/gallery_08.jpg\" alt=\"\" />\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"modal fade\" id=\"11\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("                                    <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                                        <div class=\"modal-content\">\n");
      out.write("                                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">×</span></button>\n");
      out.write("                                            <div class=\"modal-body\">\n");
      out.write("                                                <img src=\"recursos/images/gallery_08.jpg\" alt=\"\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-12 description\">\n");
      out.write("                                                <h4></h4>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4 col-sm-6 co-xs-12 gal-item\">\n");
      out.write("                            <div class=\"box\">\n");
      out.write("                                <a href=\"#\" data-toggle=\"modal\" data-target=\"#12\">\n");
      out.write("                                    <img src=\"recursos/images/1.jpg\" alt=\"\" />\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"modal fade\" id=\"12\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("                                    <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                                        <div class=\"modal-content\">\n");
      out.write("                                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">×</span></button>\n");
      out.write("                                            <div class=\"modal-body\">\n");
      out.write("                                                <img src=\"recursos/images/1.jpg\" alt=\"\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-12 description\">\n");
      out.write("                                                <h4></h4>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4 col-sm-6 co-xs-12 gal-item\">\n");
      out.write("                            <div class=\"box\">\n");
      out.write("                                <a href=\"#\" data-toggle=\"modal\" data-target=\"#13\">\n");
      out.write("                                    <img src=\"recursos/images/gallery_10.jpg\" alt=\"\" />\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"modal fade\" id=\"13\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("                                    <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                                        <div class=\"modal-content\">\n");
      out.write("                                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">×</span></button>\n");
      out.write("                                            <div class=\"modal-body\">\n");
      out.write("                                                <img src=\"recursos/images/gallery_10.jpg\" alt=\"\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-12 description\">\n");
      out.write("                                                <h4></h4>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("            \n");
      out.write("    <div id=\"blog-\" class=\"blog-main pad-top-100 pad-bottom-100 parallax\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("                    <h2 class=\"block-title text-center\"> </h2> <div class=\"blog-btn-v\"></div></div></div></div></div>\n");
      out.write("   \n");
      out.write("                            <div class=\"panel-footer\"></div>\n");
      out.write("                 \n");
      out.write("                            <div class=\"panel-footer\">\n");
      out.write("                             \n");
      out.write("                            </div>\n");
      out.write("                        \n");
      out.write("   \n");
      out.write("\n");
      out.write("    <div id=\"banner\" class=\"reservations-main pad-top-100 pad-bottom-100\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"form-reservations-box\">\n");
      out.write("                    <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("                        <div class=\"wow fadeIn\" data-wow-duration=\"1s\" data-wow-delay=\"0.1s\">\n");
      out.write("                            <h2 class=\"block-title text-center\"><br>\n");
      out.write("\t\t\t\t\t\tIngreso de Datos\t\t\t\n");
      out.write("\t\t\t\t\t</h2>\n");
      out.write("                        </div>\n");
      out.write("                        <h4 class=\"form-title\">PULSA LA TECLA REGISTRAR PARA CREAR UN USUARIO O ADMINISTRADOR </h4> <br>\n");
      out.write("                        <p>¡GRACIAS POR SU PREFERENCIA!</p>\n");
      out.write("\n");
      out.write("                         \n");
      out.write("                            \n");
      out.write("                                <div class=\"reserve-book-btn text-center\">\n");
      out.write("                                <form action=\"#!\">\n");
      out.write("                                     <center><button type=\"submit\" class=\"btn btn-danger\" name=\"registro\"  value=\"registro\">Registrarme</button></center>\n");
      out.write("                                     <br><br></form>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            \n");
      out.write("                     \n");
      out.write("                       \n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("         \n");
      out.write("        </div>\n");
      out.write("  \n");
      out.write("   \n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"footer-box pad-top-70\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"footer-in-main\">\n");
      out.write("                        <div class=\"footer-logo\">\n");
      out.write("                            <div class=\"text-center\">\n");
      out.write("                                <img src=\"recursos/images/CasaMar.png\"  width=\"350\" height=\"200\" alt=\"\" >\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\n");
      out.write("                            <div class=\"footer-box-a\">\n");
      out.write("                                <h3>Sobre nosotros</h3>\n");
      out.write("                                \n");
      out.write("                                <p>Nuestro hotel cuanta con todas las instalciones necesarias para que puedas tener unas de las mejores experiencias de estadia de tu vida.\n");
      out.write("                                Contamos con certificados calificados por asociaciones que hacen que nuestro hotel sea el mejor en el mercado </p>\n");
      out.write("                                <p>Puedes Encontrarnos en nuestras redes sociales.</p>\n");
      out.write("                                <ul class=\"socials-box footer-socials pull-left\">\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"#\">\n");
      out.write("                                            <div class=\"social-circle-border\">casamarhotel@gamai.com<i class=\"fa  fa-facebook\"></i></div>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"#\">\n");
      out.write("                                            <div class=\"social-circle-border\"><i class=\"fa fa-twitter\"></i></div>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"#\">\n");
      out.write("                                            <div class=\"social-circle-border\"><i class=\"fa fa-google-plus\"></i></div>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                       \n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                         \n");
      out.write("                        </div>\n");
      out.write("                      \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                           <div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\n");
      out.write("                            <div class=\"footer-box-a\">\n");
      out.write("                                <h3>Sobre nosotros</h3>\n");
      out.write("                                \n");
      out.write("                                <p>Nuestro hotel cuanta con todas las instalciones necesarias para que puedas tener unas de las mejores experiencias de estadia de tu vida.\n");
      out.write("                                Contamos con certificados calificados por asociaciones que hacen que nuestro hotel sea el mejor en el mercado </p>\n");
      out.write("                                <p>Puedes Encontrarnos en nuestras redes sociales.</p>\n");
      out.write("                                <ul class=\"socials-box footer-socials pull-left\">\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"#\">\n");
      out.write("                                            <div class=\"social-circle-border\">casamarhotel@gamai.com<i class=\"fa  fa-facebook\"></i></div>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"#\">\n");
      out.write("                                            <div class=\"social-circle-border\"><i class=\"fa fa-twitter\"></i></div>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"#\">\n");
      out.write("                                            <div class=\"social-circle-border\"><i class=\"fa fa-google-plus\"></i></div>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                       \n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                         \n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("                  \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("         \n");
      out.write("            <div id=\"copyright\" class=\"copyright-main\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("                            <h6 class=\"copy-title\"> Copyright &copy;<a href=\"#\" target=\"_blank\"></a> </h6>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                  \n");
      out.write("                </div>\n");
      out.write("           \n");
      out.write("            </div>\n");
      out.write("         \n");
      out.write("        </div>\n");
      out.write("   \n");
      out.write("    <script src=\"recursos/js/all.js\"></script>\n");
      out.write("    <script src=\"recursos/js/bootstrap.min.js\"></script>\n");
      out.write("   \n");
      out.write("    <script src=\"recursos/js/custom.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
